use super::*;
use xsd_proc::const_qname;
const_qname!("attributeFormDefault");
const_qname!("targetNamespace");
const_qname!("const_qnameibuteFormDefault");
const_qname!("blockDefault");
const_qname!("elementFormDefault");
const_qname!("finalDefault");
const_qname!("version");
const_qname!("id");
const_qname!("abstract");
const_qname!("block");
const_qname!("fixed");
const_qname!("default");
const_qname!("final");
const_qname!("form");
const_qname!("substitutionGroup");
const_qname!("ref");
const_qname!("maxOccurs");
const_qname!("minOccurs");
const_qname!("name");
const_qname!("type");
const_qname!("mixed");
